FROM python:3.12-slim

# -----------------------------------------------------
# Install system dependencies
# -----------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential \
    && rm -rf /var/lib/apt/lists/*

# -----------------------------------------------------
# Install Poetry
# -----------------------------------------------------
ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | python3 -

ENV POETRY_VIRTUALENVS_IN_PROJECT=true
ENV POETRY_NO_INTERACTION=1
ENV POETRY_CACHE_DIR='/tmp/poetry-cache'

WORKDIR /app/frontend

# -----------------------------------------------------
# Copy pyproject + lock files
# -----------------------------------------------------
COPY frontend/pyproject.toml frontend/poetry.lock ./

# -----------------------------------------------------
# Install deps
# -----------------------------------------------------
RUN poetry install --no-root

# -----------------------------------------------------
# Copy actual frontend source
# -----------------------------------------------------
COPY frontend /app/frontend

EXPOSE 8501
CMD ["poetry", "run", "streamlit", "run", "chat.py", \
    "--server.headless=true", \
    "--server.address=0.0.0.0", \
    "--server.port=8501", \
    "--server.enableWebsocketCompression=false", \
    "--server.enableCORS=false"]
